DECLARE
   N EMPLOYEE7.ENO%TYPE  := &N;
   DG EMPLOYEE7.DGN%TYPE;
BEGIN
  SELECT DGN INTO DG FROM EMPLOYEE7 WHERE ENO = N;
    IF DG IN('MANAGER') THEN
       UPDATE EMPLOYEE7 SET SAL = SAL+2000 WHERE ENO = N;
    ELSIF DG IN('hr') THEN
       UPDATE EMPLOYEE7 SET SAL = SAL+1000 WHERE ENO = N;
    ELSE
       UPDATE EMPLOYEE7 SET SAL = SAL+500 WHERE ENO=N;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Table updated');
END;